apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  namespace: notes-app
spec:
  selector:
    app: notes-app
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30008
